apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- resources/clusterrole/forge-kyvernoadmin-policies.yaml
- resources/clusterrole/forge-kyvernoadmin-policyreport.yaml
- resources/clusterrole/forge-kyvernoadmin-reportchangerequest.yaml
- resources/clusterrole/forge-kyvernocustomresources.yaml
- resources/clusterrole/forge-kyvernogeneratecontroller.yaml
- resources/clusterrole/forge-kyvernoleaderelection.yaml
- resources/clusterrole/forge-kyvernopolicycontroller.yaml
- resources/clusterrole/forge-kyvernouserinfo.yaml
- resources/clusterrole/forge-kyvernowebhook.yaml
- resources/clusterrolebinding/forge-kyvernocustomresources.yaml
- resources/clusterrolebinding/forge-kyvernogeneratecontroller.yaml
- resources/clusterrolebinding/forge-kyvernoleaderelection.yaml
- resources/clusterrolebinding/forge-kyvernopolicycontroller.yaml
- resources/clusterrolebinding/forge-kyvernouserinfo.yaml
- resources/clusterrolebinding/forge-kyvernowebhook.yaml
- resources/configmap/forge-kyverno-metrics.yaml
- resources/configmap/forge-kyverno.yaml
- resources/customresourcedefinition/clusterpolicieskyvernoio.yaml
- resources/customresourcedefinition/clusterpolicyreportswgpolicyk8sio.yaml
- resources/customresourcedefinition/clusterreportchangerequestskyvernoio.yaml
- resources/customresourcedefinition/generaterequestskyvernoio.yaml
- resources/customresourcedefinition/policieskyvernoio.yaml
- resources/customresourcedefinition/policyreportswgpolicyk8sio.yaml
- resources/customresourcedefinition/reportchangerequestskyvernoio.yaml
- resources/deployment/forge-kyverno.yaml
- resources/service/forge-kyverno-svc-metrics.yaml
- resources/service/forge-kyverno-svc.yaml
- resources/serviceaccount/forge-kyverno.yaml
