apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "4"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"prometheus-operator-operator"},"name":"prometheus-operator-operator","namespace":"solar-system"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"prometheus-operator-operator"}},"template":{"metadata":{"labels":{"app":"prometheus-operator-operator"}},"spec":{"containers":[{"args":["--kubelet-service=kube-system/prometheus-operator-kubelet","--localhost=127.0.0.1","--prometheus-config-reloader=quay.io/prometheus-operator/prometheus-config-reloader:v0.45.0","--config-reloader-cpu=100m","--config-reloader-memory=50Mi","--web.enable-tls=true","--web.cert-file=/cert/cert","--web.key-file=/cert/key","--web.listen-address=:10250","--web.tls-min-version=VersionTLS13"],"image":"quay.io/prometheus-operator/prometheus-operator:v0.45.0","imagePullPolicy":"IfNotPresent","name":"prometheus-operator","ports":[{"containerPort":10250,"name":"https"}],"resources":{},"securityContext":{"allowPrivilegeEscalation":false,"readOnlyRootFilesystem":true},"volumeMounts":[{"mountPath":"/cert","name":"tls-secret","readOnly":true}]}],"securityContext":{"fsGroup":65534,"runAsGroup":65534,"runAsNonRoot":true,"runAsUser":65534},"serviceAccountName":"prometheus-operator-operator","volumes":[{"name":"tls-secret","secret":{"defaultMode":420,"secretName":"prometheus-operator-admission"}}]}}}}
  creationTimestamp: "2020-08-06T13:45:16Z"
  generation: 4
  labels:
    app: prometheus-operator-operator
  name: prometheus-operator-operator
  namespace: solar-system
  resourceVersion: "267263662"
  selfLink: /apis/apps/v1/namespaces/solar-system/deployments/prometheus-operator-operator
  uid: 0f2ba1d5-d7eb-11ea-b3d3-02764ebdfbfb
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: prometheus-operator-operator
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: prometheus-operator-operator
    spec:
      containers:
      - args:
        - --kubelet-service=kube-system/prometheus-operator-kubelet
        - --localhost=127.0.0.1
        - --prometheus-config-reloader=quay.io/prometheus-operator/prometheus-config-reloader:v0.45.0
        - --config-reloader-cpu=100m
        - --config-reloader-memory=50Mi
        - --web.enable-tls=true
        - --web.cert-file=/cert/cert
        - --web.key-file=/cert/key
        - --web.listen-address=:10250
        - --web.tls-min-version=VersionTLS13
        image: quay.io/prometheus-operator/prometheus-operator:v0.45.0
        imagePullPolicy: IfNotPresent
        name: prometheus-operator
        ports:
        - containerPort: 10250
          name: https
          protocol: TCP
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /cert
          name: tls-secret
          readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 65534
        runAsGroup: 65534
        runAsNonRoot: true
        runAsUser: 65534
      serviceAccount: prometheus-operator-operator
      serviceAccountName: prometheus-operator-operator
      terminationGracePeriodSeconds: 30
      volumes:
      - name: tls-secret
        secret:
          defaultMode: 420
          secretName: prometheus-operator-admission
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2020-08-06T13:45:16Z"
    lastUpdateTime: "2021-03-01T18:27:49Z"
    message: ReplicaSet "prometheus-operator-operator-76c566b8d9" has successfully
      progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2021-12-16T15:07:27Z"
    lastUpdateTime: "2021-12-16T15:07:27Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 4
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
