# apiVersion: kustomize.config.k8s.io/v1beta1
# kind: Kustomization

# resources:
# - ../base/
# - overlays/best-practices/disallow_default_namespace/disallow_default_namespace.yaml
# - overlays/best-practices/disallow_latest_tag/disallow_latest_tag.yaml
# - overlays/best-practices/require_labels/require_labels.yaml
# - overlays/best-practices/require_pod_request_limits/require_pod_request_limits.yaml
# - overlays/best-practices/add_network_policy
# - overlays/best-practices/add_ns_quota.yaml