apiVersion: v1
kind: Pod
metadata:
  annotations:
    helm.sh/hook: test
  labels:
    app.kubernetes.io/component: kyverno
    app.kubernetes.io/instance: kyverno
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kyverno-test
    app.kubernetes.io/part-of: kyverno
    app.kubernetes.io/version: v2.1.0
    helm.sh/chart: kyverno-v2.1.0
  name: kyverno-test
spec:
  containers:
  - command:
    - /bin/sh
    - -c
    - |
      sleep 20 ; wget -O- -S --no-check-certificate https://kyverno-svc:443/health/liveness
    image: busybox
    imagePullPolicy: IfNotPresent
    name: wget
  - command:
    - /bin/sh
    - -c
    - |
      sleep 20 ; wget -O- -S --no-check-certificate http://kyverno-svc-metrics:8000/metrics
    image: busybox
    imagePullPolicy: IfNotPresent
    name: wget-metrics
  restartPolicy: Never

