apiVersion: v1
kind: Service
metadata:
  labels:
    app: kyverno
    app.kubernetes.io/component: kyverno
    app.kubernetes.io/instance: forge
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kyverno
    app.kubernetes.io/part-of: kyverno
    app.kubernetes.io/version: v2.1.0
    helm.sh/chart: kyverno-v2.1.0
  name: forge-kyverno-svc-metrics
  namespace: forge
spec:
  ports:
  - name: metrics-port
    port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: kyverno
    app.kubernetes.io/instance: forge
    app.kubernetes.io/name: kyverno
  type: ClusterIP

