apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app: kyverno
    app.kubernetes.io/component: kyverno
    app.kubernetes.io/instance: forge
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kyverno
    app.kubernetes.io/part-of: kyverno
    app.kubernetes.io/version: v2.1.0
    helm.sh/chart: kyverno-v2.1.0
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
  name: forge-kyverno:admin-policyreport
rules:
- apiGroups:
  - wgpolicyk8s.io/v1alpha2
  resources:
  - policyreport
  - clusterpolicyreport
  verbs:
  - '*'

