apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../base
- best-practices/disallow_default_namespace/disallow_default_namespace.yaml
- best-practices/disallow_latest_tag/disallow_latest_tag.yaml
- best-practices/require_labels/require_labels.yaml
- best-practices/require_pod_requests_limits/require_pod_requests_limits.yaml
- best-practices/add_network_policy.yaml
- best-practices/add_ns_quota.yaml