apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: kyverno
    app.kubernetes.io/component: kyverno
    app.kubernetes.io/instance: forge
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kyverno
    app.kubernetes.io/part-of: kyverno
    app.kubernetes.io/version: v2.1.0
    helm.sh/chart: kyverno-v2.1.0
  name: forge-kyverno
  namespace: default

