apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- customresourcedefinition-clusterpolicies.kyverno.io.yaml
- customresourcedefinition-clusterpolicyreports.wgpolicyk8s.io.yaml
- customresourcedefinition-clusterreportchangerequests.kyverno.io.yaml
- customresourcedefinition-generaterequests.kyverno.io.yaml
- customresourcedefinition-policies.kyverno.io.yaml
- customresourcedefinition-policyreports.wgpolicyk8s.io.yaml
- customresourcedefinition-reportchangerequests.kyverno.io.yaml
